import { createFileRoute, Link } from "@tanstack/react-router";
import { ShieldCheck, ArrowLeft, Lock, HardDrive, UserCheck } from "lucide-react";

export const Route = createFileRoute("/privacy")({
  component: PrivacyPolicyPage,
});

export function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0C] text-slate-100 flex flex-col font-sans selection:bg-indigo-500 selection:text-white">
      {/* Navigation Header */}
      <header className="sticky top-0 z-30 border-b border-white/10 bg-[#0A0A0C]/80 backdrop-blur-md px-6 py-4 flex items-center justify-between">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to COSY.AI</span>
        </Link>
        <div className="flex items-center gap-2 text-xs font-mono text-indigo-400 bg-indigo-500/10 border border-indigo-500/20 px-3 py-1 rounded-full">
          <ShieldCheck className="w-3.5 h-3.5" />
          <span>App Store & GDPR Compliant</span>
        </div>
      </header>

      {/* Content Body */}
      <main className="flex-1 max-w-3xl mx-auto px-6 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white mb-2">Privacy Policy</h1>
          <p className="text-sm text-slate-400">Last updated: July 27, 2026 • Version 2.4.0</p>
        </div>

        <section className="space-y-4 bg-white/5 border border-white/10 p-6 rounded-2xl">
          <div className="flex items-center gap-3 text-indigo-400 font-semibold">
            <Lock className="w-5 h-5" />
            <h2 className="text-lg text-white">Data Protection & Privacy Overview</h2>
          </div>
          <p className="text-sm text-slate-300 leading-relaxed">
            COSY.AI is engineered with privacy-by-design principles. We
            prioritize local browser execution, encrypted token handling, and strict data
            minimization across all mobile, web, and native desktop runtimes.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-white">1. Information We Collect</h2>
          <ul className="list-disc list-inside space-y-2 text-sm text-slate-300 leading-relaxed">
            <li>
              <strong>Account Credentials:</strong> Email address and authentication tokens via
              Supabase Auth.
            </li>
            <li>
              <strong>Visual Artifacts & Prompts:</strong> Code snippets, design prompts, and canvas
              state required to render your applications.
            </li>
            <li>
              <strong>Device & PWA Telemetry:</strong> Anonymous performance diagnostics, viewport
              dimensions, and PWA installation state.
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-emerald-400 font-semibold">
            <HardDrive className="w-5 h-5" />
            <h2 className="text-lg text-white">2. Local Storage & Offline PWA Cache</h2>
          </div>
          <p className="text-sm text-slate-300 leading-relaxed">
            Your local canvas drafts, preferences, and offline PWA assets are stored directly on
            your client device using browser{" "}
            <code className="text-xs bg-white/10 px-1.5 py-0.5 rounded text-emerald-300 font-mono">
              localStorage
            </code>{" "}
            and IndexedDB. We never sell or monetize your personal code or prompt history.
          </p>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-indigo-400 font-semibold">
            <UserCheck className="w-5 h-5" />
            <h2 className="text-lg text-white">3. Your Data Rights & Deletion</h2>
          </div>
          <p className="text-sm text-slate-300 leading-relaxed">
            Under GDPR and CCPA, you retain full ownership of all code generated by COSY.AI. You can
            request complete account and data deletion at any time by contacting our support team at{" "}
            <a href="mailto:support@cosyapp.dev" className="text-indigo-400 underline">
              support@cosyapp.dev
            </a>
            .
          </p>
        </section>
      </main>

      <footer className="border-t border-white/10 py-6 px-6 text-center text-xs text-slate-500">
        © 2026 COSY.AI. All rights reserved.
      </footer>
    </div>
  );
}
