/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesSlugRouteImport } from './routes/templates.$slug'
import { Route as DevBuilderPlaygroundRouteImport } from './routes/dev.builder-playground'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiStatusRouteImport } from './routes/api/ai-status'
import { Route as AArtifactIdRouteImport } from './routes/a.$artifactId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as PreviewArtifactIdSplatRouteImport } from './routes/preview.$artifactId.$'
import { Route as AArtifactIdEmbedRouteImport } from './routes/a.$artifactId.embed'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as PreviewArtifactIdChar126TokenSplatRouteImport } from './routes/preview.$artifactId.~.$token.$'
import { Route as ApiProjectsArtifactIdFilesSplatRouteImport } from './routes/api/projects.$artifactId.files.$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TemplatesRoute,
} as any)
const DevBuilderPlaygroundRoute = DevBuilderPlaygroundRouteImport.update({
  id: '/dev/builder-playground',
  path: '/dev/builder-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai-status',
  path: '/api/ai-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AArtifactIdRoute = AArtifactIdRouteImport.update({
  id: '/a/$artifactId',
  path: '/a/$artifactId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PreviewArtifactIdSplatRoute = PreviewArtifactIdSplatRouteImport.update({
  id: '/preview/$artifactId/$',
  path: '/preview/$artifactId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AArtifactIdEmbedRoute = AArtifactIdEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => AArtifactIdRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PreviewArtifactIdChar126TokenSplatRoute =
  PreviewArtifactIdChar126TokenSplatRouteImport.update({
    id: '/preview/$artifactId/~/$token/$',
    path: '/preview/$artifactId/~/$token/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsArtifactIdFilesSplatRoute =
  ApiProjectsArtifactIdFilesSplatRouteImport.update({
    id: '/api/projects/$artifactId/files/$',
    path: '/api/projects/$artifactId/files/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$artifactId': typeof AArtifactIdRouteWithChildren
  '/api/ai-status': typeof ApiAiStatusRoute
  '/api/chat': typeof ApiChatRoute
  '/dev/builder-playground': typeof DevBuilderPlaygroundRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/a/$artifactId/embed': typeof AArtifactIdEmbedRoute
  '/preview/$artifactId/$': typeof PreviewArtifactIdSplatRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/api/projects/$artifactId/files/$': typeof ApiProjectsArtifactIdFilesSplatRoute
  '/preview/$artifactId/~/$token/$': typeof PreviewArtifactIdChar126TokenSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$artifactId': typeof AArtifactIdRouteWithChildren
  '/api/ai-status': typeof ApiAiStatusRoute
  '/api/chat': typeof ApiChatRoute
  '/dev/builder-playground': typeof DevBuilderPlaygroundRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/a/$artifactId/embed': typeof AArtifactIdEmbedRoute
  '/preview/$artifactId/$': typeof PreviewArtifactIdSplatRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/api/projects/$artifactId/files/$': typeof ApiProjectsArtifactIdFilesSplatRoute
  '/preview/$artifactId/~/$token/$': typeof PreviewArtifactIdChar126TokenSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$artifactId': typeof AArtifactIdRouteWithChildren
  '/api/ai-status': typeof ApiAiStatusRoute
  '/api/chat': typeof ApiChatRoute
  '/dev/builder-playground': typeof DevBuilderPlaygroundRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/a/$artifactId/embed': typeof AArtifactIdEmbedRoute
  '/preview/$artifactId/$': typeof PreviewArtifactIdSplatRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/api/projects/$artifactId/files/$': typeof ApiProjectsArtifactIdFilesSplatRoute
  '/preview/$artifactId/~/$token/$': typeof PreviewArtifactIdChar126TokenSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/support'
    | '/templates'
    | '/terms'
    | '/builder'
    | '/dashboard'
    | '/a/$artifactId'
    | '/api/ai-status'
    | '/api/chat'
    | '/dev/builder-playground'
    | '/templates/$slug'
    | '/chat/$threadId'
    | '/a/$artifactId/embed'
    | '/preview/$artifactId/$'
    | '/chat/'
    | '/api/projects/$artifactId/files/$'
    | '/preview/$artifactId/~/$token/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/support'
    | '/templates'
    | '/terms'
    | '/builder'
    | '/dashboard'
    | '/a/$artifactId'
    | '/api/ai-status'
    | '/api/chat'
    | '/dev/builder-playground'
    | '/templates/$slug'
    | '/chat/$threadId'
    | '/a/$artifactId/embed'
    | '/preview/$artifactId/$'
    | '/chat'
    | '/api/projects/$artifactId/files/$'
    | '/preview/$artifactId/~/$token/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/support'
    | '/templates'
    | '/terms'
    | '/_authenticated/builder'
    | '/_authenticated/dashboard'
    | '/a/$artifactId'
    | '/api/ai-status'
    | '/api/chat'
    | '/dev/builder-playground'
    | '/templates/$slug'
    | '/_authenticated/chat/$threadId'
    | '/a/$artifactId/embed'
    | '/preview/$artifactId/$'
    | '/_authenticated/chat/'
    | '/api/projects/$artifactId/files/$'
    | '/preview/$artifactId/~/$token/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  TermsRoute: typeof TermsRoute
  AArtifactIdRoute: typeof AArtifactIdRouteWithChildren
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiChatRoute: typeof ApiChatRoute
  DevBuilderPlaygroundRoute: typeof DevBuilderPlaygroundRoute
  PreviewArtifactIdSplatRoute: typeof PreviewArtifactIdSplatRoute
  ApiProjectsArtifactIdFilesSplatRoute: typeof ApiProjectsArtifactIdFilesSplatRoute
  PreviewArtifactIdChar126TokenSplatRoute: typeof PreviewArtifactIdChar126TokenSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/dev/builder-playground': {
      id: '/dev/builder-playground'
      path: '/dev/builder-playground'
      fullPath: '/dev/builder-playground'
      preLoaderRoute: typeof DevBuilderPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-status': {
      id: '/api/ai-status'
      path: '/api/ai-status'
      fullPath: '/api/ai-status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$artifactId': {
      id: '/a/$artifactId'
      path: '/a/$artifactId'
      fullPath: '/a/$artifactId'
      preLoaderRoute: typeof AArtifactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/preview/$artifactId/$': {
      id: '/preview/$artifactId/$'
      path: '/preview/$artifactId/$'
      fullPath: '/preview/$artifactId/$'
      preLoaderRoute: typeof PreviewArtifactIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$artifactId/embed': {
      id: '/a/$artifactId/embed'
      path: '/embed'
      fullPath: '/a/$artifactId/embed'
      preLoaderRoute: typeof AArtifactIdEmbedRouteImport
      parentRoute: typeof AArtifactIdRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/preview/$artifactId/~/$token/$': {
      id: '/preview/$artifactId/~/$token/$'
      path: '/preview/$artifactId/~/$token/$'
      fullPath: '/preview/$artifactId/~/$token/$'
      preLoaderRoute: typeof PreviewArtifactIdChar126TokenSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$artifactId/files/$': {
      id: '/api/projects/$artifactId/files/$'
      path: '/api/projects/$artifactId/files/$'
      fullPath: '/api/projects/$artifactId/files/$'
      preLoaderRoute: typeof ApiProjectsArtifactIdFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuilderRoute: AuthenticatedBuilderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TemplatesRouteChildren {
  TemplatesSlugRoute: typeof TemplatesSlugRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesSlugRoute: TemplatesSlugRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface AArtifactIdRouteChildren {
  AArtifactIdEmbedRoute: typeof AArtifactIdEmbedRoute
}

const AArtifactIdRouteChildren: AArtifactIdRouteChildren = {
  AArtifactIdEmbedRoute: AArtifactIdEmbedRoute,
}

const AArtifactIdRouteWithChildren = AArtifactIdRoute._addFileChildren(
  AArtifactIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  TermsRoute: TermsRoute,
  AArtifactIdRoute: AArtifactIdRouteWithChildren,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiChatRoute: ApiChatRoute,
  DevBuilderPlaygroundRoute: DevBuilderPlaygroundRoute,
  PreviewArtifactIdSplatRoute: PreviewArtifactIdSplatRoute,
  ApiProjectsArtifactIdFilesSplatRoute: ApiProjectsArtifactIdFilesSplatRoute,
  PreviewArtifactIdChar126TokenSplatRoute:
    PreviewArtifactIdChar126TokenSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
